/* Generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef AVICREATOR_H
#define AVICREATOR_H

/* Warning: Automatically generated C bindings for Avicreator */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct EngineHandle EngineHandle;

/**
 * Creates a new engine instance handle.
 * The returned pointer must be destroyed with `avicreator_engine_destroy`.
 */
struct EngineHandle *avicreator_engine_create(void);

/**
 * Frees an engine instance handle created by `avicreator_engine_create`.
 */
void avicreator_engine_destroy(struct EngineHandle *engine);

/**
 * Explicit string deallocator for strings returned by FFI methods.
 */
void avicreator_free_string(char *s);

/**
 * Explicit f32 buffer deallocator to prevent cross-boundary memory leaks.
 */
void avicreator_free_f32_buffer(float *ptr, uintptr_t len);

/**
 * Explicit u32 buffer deallocator to prevent cross-boundary memory leaks.
 */
void avicreator_free_u32_buffer(uint32_t *ptr, uintptr_t len);

/**
 * Sets the base mesh geometry for the avatar engine.
 * Returns 0 on success, -1 if engine pointer is null, -2 if lengths are invalid.
 */
int32_t avicreator_engine_set_mesh(struct EngineHandle *engine,
                                   const float *positions,
                                   uintptr_t pos_len,
                                   const float *normals,
                                   uintptr_t norm_len,
                                   const float *uvs,
                                   uintptr_t uv_len,
                                   const uint32_t *indices,
                                   uintptr_t idx_len);

/**
 * Adds a morph target to the engine.
 * Returns 0 on success, -1 if engine/name/deltas is null, -2 if length invalid.
 */
int32_t avicreator_engine_add_morph_target(struct EngineHandle *engine,
                                           const char *name,
                                           const float *deltas,
                                           uintptr_t delta_len);

/**
 * Sets weight for a morph target.
 */
int32_t avicreator_engine_set_morph_weight(struct EngineHandle *engine,
                                           const char *name,
                                           float weight);

/**
 * Computes deformed positions and copies result into output float buffer.
 * Returns 0 on success, -1 if engine is null, -2 if no base mesh, -3 if buffer is too small.
 */
int32_t avicreator_engine_compute_deformed_positions(struct EngineHandle *engine,
                                                     float *out_positions,
                                                     uintptr_t out_len);

/**
 * Recalculates normals and fills out_normals buffer.
 */
int32_t avicreator_engine_recalculate_normals(struct EngineHandle *engine,
                                              float *out_normals,
                                              uintptr_t out_len);

/**
 * Gets the vertex count of the current base mesh.
 */
uintptr_t avicreator_engine_get_vertex_count(struct EngineHandle *engine);

/**
 * Gets the index count of the current base mesh.
 */
uintptr_t avicreator_engine_get_index_count(struct EngineHandle *engine);

/**
 * Normalizes vertex weights buffer in place.
 */
int32_t avicreator_normalize_weights(float *weights, uintptr_t len, float epsilon);

/**
 * Validates manifest JSON. Returns 1 if valid, 0 if invalid.
 */
int32_t avicreator_validate_manifest_json(const char *json_str);

/**
 * Returns C string version of Avicreator library.
 * Caller must free string using `avicreator_free_string`.
 */
char *avicreator_version(void);

#endif  /* AVICREATOR_H */
